version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urando:/dev/random:ro
    ports:
      - 8080:80
    environment:
       MB_DB_TYPE: postgres
       MB_DB_DBNAME: metabaseappdb
       MB_DB_PORT: 5432
       MB_DB_USER: hayden-loc
       MB_DB_PASS: Mrshoogknight13$
       MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:8080/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: hayden-loc
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: Mrshoogknight13$
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
